owner: alprimus
repo: uptime
user-agent: alprimus
sites:
  - name: Alprimus Login
    url: https://alprimus.com/login
status-website:
  cname: status.alprimus.com
  logoUrl: https://alprimus.com/favicon.ico
  name: Alprimus Status
  introTitle: "Alprimus Uptime Status"
  introMessage: This is the status page for Alprimus, showing the availability of the login endpoint.
  navbar:
    - title: Status
      href: /
    - title: Alprimus
      href: https://alprimus.com
assignees:
  - alprimus
